#!/bin/bash

# Setup an environment to build natively (supports Linux and Windows)

set -eu

source ./scripts/build-common-setup.sh native

CMAKE_FLAGS=(-DCMAKE_INSTALL_PREFIX="$DEPS_INSTALL_DIR")

setup_deps "$DEPS_SOURCE_DIR" "$DEPS_BUILD_DIR" "${CMAKE_FLAGS[@]}"

configure_and_build
