#!/bin/bash

# Setup an environment to build from Linux to Windows using LLVM-MinGW

set -eu

source ./scripts/build-common-setup.sh llvm-mingw-ucrt

LLVM_MINGW_VERSION=22.1.7
LLVM_MINGW_URL=https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-ubuntu-22.04-x86_64.tar.xz
LLVM_MINGW_ARCHIVE=$(basename "$LLVM_MINGW_URL")

if [ ! -d "$DEPS_SOURCE_DIR/llvm-mingw" ]; then
    mkdir -p "$DEPS_SOURCE_DIR/llvm-mingw"
    if [ ! -f "$DEPS_SOURCE_DIR/$LLVM_MINGW_ARCHIVE" ]; then
        echo "Downloading LLVM-MinGW $LLVM_MINGW_VERSION..."
        wget --output-document="$DEPS_SOURCE_DIR/$LLVM_MINGW_ARCHIVE" \
            $LLVM_MINGW_URL
    fi
    echo "Extracting LLVM-MinGW $LLVM_MINGW_VERSION..."
    tar --extract --file="$DEPS_SOURCE_DIR/$LLVM_MINGW_ARCHIVE" \
        --directory="$DEPS_SOURCE_DIR/llvm-mingw" --strip-components=1
fi

TOOLCHAIN_ARGS=(
    --toolchain="$(realpath cmake/Toolchains/LLVM-MinGW-UCRT.cmake)"
    -DLLVM_MINGW_UCRT_DIR="$(realpath $DEPS_SOURCE_DIR/llvm-mingw)"
)

CMAKE_FLAGS=("${TOOLCHAIN_ARGS[@]}")

setup_deps "$DEPS_SOURCE_DIR" "$DEPS_BUILD_DIR" "${CMAKE_FLAGS[@]}"

configure_and_build "${TOOLCHAIN_ARGS[@]}"
