#!/bin/bash

set -eu

source ./scripts/build-common-setup.sh llvm-mingw-ucrt

if [ ! -d "$DEPS_SOURCE_DIR/llvm-mingw" ]; then
    mkdir -p "$DEPS_SOURCE_DIR/llvm-mingw"
    if [ ! -f "$DEPS_SOURCE_DIR/llvm-mingw-20260407-ucrt-ubuntu-22.04-x86_64.tar.xz" ]; then
        echo "Downloading LLVM-MinGW 22.1.3..."
        wget --output-document="$DEPS_SOURCE_DIR/llvm-mingw-20260407-ucrt-ubuntu-22.04-x86_64.tar.xz" \
            https://github.com/mstorsjo/llvm-mingw/releases/download/20260407/llvm-mingw-20260407-ucrt-ubuntu-22.04-x86_64.tar.xz
    fi
    echo "Extracting LLVM-MinGW 22.1.3..."
    tar --extract --file="$DEPS_SOURCE_DIR/llvm-mingw-20260407-ucrt-ubuntu-22.04-x86_64.tar.xz" \
        --directory="$DEPS_SOURCE_DIR/llvm-mingw" --strip-components=1
fi

TOOLCHAIN_ARGS=(
    --toolchain="$(realpath cmake/Toolchains/LLVM-MinGW-UCRT.cmake)"
    -DLLVM_MINGW_UCRT_DIR="$(realpath $DEPS_SOURCE_DIR/llvm-mingw)"
)

CMAKE_FLAGS=(-DCMAKE_INSTALL_PREFIX="$DEPS_INSTALL_DIR")
CMAKE_FLAGS+=("${TOOLCHAIN_ARGS[@]}")

setup_deps "$DEPS_SOURCE_DIR" "$DEPS_BUILD_DIR" "${CMAKE_FLAGS[@]}"

configure_and_build "${TOOLCHAIN_ARGS[@]}"
